[tools]
"pipx:bump-my-version" = "latest"
powershell = "latest"
uv = "latest"

[tasks.release]
description = "tag and push a release"
shell = "pwsh -c"
alias = "r"
run_windows = '''
$ver = bump-my-version show --increment patch new_version
echo $ver > ./version
pwsh -c ./build.ps1
git add -A
git commit -am "release: $ver"
git push
git tag -a "v$ver" -m "v$ver"
git push --tags
'''

[tasks.sync]
alias = 's'
usage = 'arg "<msg>" default="sync"'
run = 'git add -A && git commit -am "{{usage.msg}}" && git pull && git push'